version: "3"

services:

  ripper:
    build:
      context: ./ripper

  # Database Server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 731b125128fa9fcc5b27f37817e5cc7ab79ce2fb
    ports:
      - 5432:5432


# Database Management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080